package com.abc.ws.bean;

// Generated 18/10/2013 04:08:51 PM by Hibernate Tools 4.0.0

/**
 * XxWabClassinfo generated by hbm2java
 */
public class XxWabClassinfo implements java.io.Serializable {

	private long classlevel3Id;
	private long classlevel1Id;
	private String classlevel1Name;
	private long classlevel2Id;
	private String classlevel2Name;
	private String classlevel3Name;

	public XxWabClassinfo() {
	}

	public XxWabClassinfo(long classlevel3Id) {
		this.classlevel3Id = classlevel3Id;
	}

	public XxWabClassinfo(long classlevel3Id, long classlevel1Id,
			String classlevel1Name, long classlevel2Id, String classlevel2Name,
			String classlevel3Name) {
		this.classlevel3Id = classlevel3Id;
		this.classlevel1Id = classlevel1Id;
		this.classlevel1Name = classlevel1Name;
		this.classlevel2Id = classlevel2Id;
		this.classlevel2Name = classlevel2Name;
		this.classlevel3Name = classlevel3Name;
	}

	public long getClasslevel3Id() {
		return this.classlevel3Id;
	}

	public void setClasslevel3Id(long classlevel3Id) {
		this.classlevel3Id = classlevel3Id;
	}

	public long getClasslevel1Id() {
		return this.classlevel1Id;
	}

	public void setClasslevel1Id(long classlevel1Id) {
		this.classlevel1Id = classlevel1Id;
	}

	public String getClasslevel1Name() {
		return this.classlevel1Name;
	}

	public void setClasslevel1Name(String classlevel1Name) {
		this.classlevel1Name = classlevel1Name;
	}

	public long getClasslevel2Id() {
		return this.classlevel2Id;
	}

	public void setClasslevel2Id(long classlevel2Id) {
		this.classlevel2Id = classlevel2Id;
	}

	public String getClasslevel2Name() {
		return this.classlevel2Name;
	}

	public void setClasslevel2Name(String classlevel2Name) {
		this.classlevel2Name = classlevel2Name;
	}

	public String getClasslevel3Name() {
		return this.classlevel3Name;
	}

	public void setClasslevel3Name(String classlevel3Name) {
		this.classlevel3Name = classlevel3Name;
	}

}
