package com.abc.ws.bean;

// Generated 18/10/2013 04:08:51 PM by Hibernate Tools 4.0.0

/**
 * XxWabProductinfo generated by hbm2java
 */
public class XxWabProductinfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private long MProductId;
	private String description;
	private String value;
	private String name;
	private long classlevel1Id;
	private long classlevel2Id;
	private long classlevel3Id;
	private float finalprice;
	private float originalprice;
	private String promo;
	private long qty;
	private String gift;
	private String newproduct;
	
	private String overview;
	private String model;
	private String color;
	private String shape;
	private String material1;
	private String material2;
	private float weight;
	private float width;
	private float height;

	public XxWabProductinfo() {
	}

	public XxWabProductinfo(long MProductId, String value, String name,
			long classlevel1Id, long classlevel2Id, long qty, String gift) {
		this.MProductId = MProductId;
		this.value = value;
		this.name = name;
		this.classlevel1Id = classlevel1Id;
		this.classlevel2Id = classlevel2Id;
		this.qty = qty;
		this.gift = gift;
	}

	public XxWabProductinfo(long MProductId, String description, String value,
			String name, long classlevel1Id, long classlevel2Id,
			long classlevel3Id, float finalprice, float originalprice, String promo, 
			long qty, String gift, String newproduct) {
		this.MProductId = MProductId;
		this.description = description;
		this.value = value;
		this.name = name;
		this.classlevel1Id = classlevel1Id;
		this.classlevel2Id = classlevel2Id;
		this.classlevel3Id = classlevel3Id;
		this.finalprice = finalprice;
		this.originalprice = originalprice;
		this.promo = promo;
		this.qty = qty;
		this.gift = gift;
		this.newproduct = newproduct;
	}

	public XxWabProductinfo(long mProductId, String description, String value,
			String name, long classlevel1Id, long classlevel2Id,
			long classlevel3Id, float finalprice, float originalprice, String promo, long qty, String gift,
			String newproduct, String overview, String model,
			String color, String shape, String material1,
			String material2, float weight, float width,
			float height) {
		MProductId = mProductId;
		this.description = description;
		this.value = value;
		this.name = name;
		this.classlevel1Id = classlevel1Id;
		this.classlevel2Id = classlevel2Id;
		this.classlevel3Id = classlevel3Id;
		this.finalprice = finalprice;
		this.originalprice = originalprice;
		this.promo = promo;
		this.qty = qty;
		this.gift = gift;
		this.newproduct = newproduct;
		this.overview = overview;
		this.model = model;
		this.color = color;
		this.shape = shape;
		this.material1 = material1;
		this.material2 = material2;
		this.weight = weight;
		this.width = width;
		this.height = height;
	}

	public long getMProductId() {
		return this.MProductId;
	}

	public void setMProductId(long MProductId) {
		this.MProductId = MProductId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getName() {
		return this.name;
	}
	
	/*
    * @return name formatted
    */
   public java.lang.String getNameFormatted() {
   	
   	if(getName()==null)
   		return "";
   	
   	return getName().replace("/", "-").replace(" ", "-").replace("---", "-").replace("--", "-").toLowerCase();
   }

	public void setName(String name) {
		this.name = name;
	}

	public long getClasslevel1Id() {
		return this.classlevel1Id;
	}

	public void setClasslevel1Id(long classlevel1Id) {
		this.classlevel1Id = classlevel1Id;
	}

	public long getClasslevel2Id() {
		return this.classlevel2Id;
	}

	public void setClasslevel2Id(long classlevel2Id) {
		this.classlevel2Id = classlevel2Id;
	}

	public long getClasslevel3Id() {
		return this.classlevel3Id;
	}

	public void setClasslevel3Id(long classlevel3Id) {
		this.classlevel3Id = classlevel3Id;
	}

	public float getFinalprice() {
		return finalprice;
	}

	public void setFinalprice(float finalprice) {
		this.finalprice = finalprice;
	}

	public float getOriginalprice() {
		return originalprice;
	}

	public void setOriginalprice(float originalprice) {
		this.originalprice = originalprice;
	}

	public String getPromo() {
		return promo;
	}

	public void setPromo(String promo) {
		this.promo = promo;
	}

	public long getQty() {
		return this.qty;
	}

	public void setQty(long qty) {
		this.qty = qty;
	}

	public String getGift() {
		return gift;
	}

	public void setGift(String gift) {
		this.gift = gift;
	}

	public String getNewproduct() {
		return newproduct;
	}

	public void setNewproduct(String newproduct) {
		this.newproduct = newproduct;
	}

	public String getOverview() {
		return overview;
	}

	public void setOverview(String overview) {
		this.overview = overview;
	}

	public String getModel() {
		return model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getColor() {
		return color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getShape() {
		return shape;
	}

	public void setShape(String shape) {
		this.shape = shape;
	}

	public String getMaterial1() {
		return material1;
	}

	public void setMaterial1(String material1) {
		this.material1 = material1;
	}

	public String getMaterial2() {
		return material2;
	}

	public void setMaterial2(String material2) {
		this.material2 = material2;
	}

	public float getWeight() {
		return weight;
	}

	public void setWeight(float weight) {
		this.weight = weight;
	}

	public float getWidth() {
		return width;
	}

	public void setWidth(float width) {
		this.width = width;
	}

	public float getHeight() {
		return height;
	}

	public void setHeight(float height) {
		this.height = height;
	}
}
