package com.abstracta.bean;

import java.math.BigDecimal;
// Generated 02/12/2013 10:07:39 AM by Hibernate Tools 3.4.0.CR1
import java.util.Date;


/**
 * CartLine generated by hbm2java
 */
public class CartLine implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Integer cartLineId;	
	private Integer cartId;
	private Integer qty;
	private Integer productId;
	private BigDecimal originalPrice;
	private Date created;
	private Integer createdby;

	public CartLine() {
	}

	public CartLine(Integer cartLineId, Integer cartId,
			Integer productId, BigDecimal originalPrice, Date created,
			Integer createdby, Integer qty) {
		this.cartLineId = cartLineId;
		this.cartId = cartId;
		this.qty = qty;
		this.productId = productId;
		this.originalPrice = originalPrice;
		this.created = created;
		this.createdby = createdby;
	}
	
	public CartLine(Integer cartId, Integer productId, BigDecimal originalPrice, 
			Date created, Integer createdby, Integer qty) {
	
		this.cartId = cartId;
		this.qty = qty;
		this.productId = productId;
		this.originalPrice = originalPrice;
		this.created = created;
		this.createdby = createdby;
	}

	public Integer getCartLineId() {
		return this.cartLineId;
	}

	public void setCartLineId(Integer cartLineId) {
		this.cartLineId = cartLineId;
	}

	public Integer getCartId() {
		return this.cartId;
	}

	public void setCartId(Integer cartId) {
		this.cartId = cartId;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public BigDecimal getOriginalPrice() {
		return this.originalPrice;
	}

	public void setOriginalPrice(BigDecimal originalPrice) {
		this.originalPrice = originalPrice;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Integer getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	public Integer getQty() {
		return qty;
	}

	public void setQty(Integer qty) {
		this.qty = qty;
	}
}
