package com.abstracta.bean;

// Generated 02/12/2013 10:07:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Cart generated by hbm2java
 */
public class Cart implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer cartId;
	private Date created;
	private Integer createdby;
	private Integer customerId;
	private Date updated;
	private Integer statusId;

	public Cart() {
	}

	public Cart(Integer cartId, Date created, Integer createdby,
			Date updated, Integer statusId) {
		this.cartId = cartId;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.statusId = statusId;
	}
	
	public Cart(Date created, Integer createdby, Integer customerId, Date updated, Integer statusId) {

		this.customerId = customerId;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.statusId = statusId;
	}

	public Cart(Integer cartId, Date created, Integer createdby,
			Integer customerId, Date updated, Integer statusId) {
		this.cartId = cartId;
		this.created = created;
		this.createdby = createdby;
		this.customerId = customerId;
		this.updated = updated;
		this.statusId = statusId;
	}

	public Integer getCartId() {
		return this.cartId;
	}

	public void setCartId(Integer cartId) {
		this.cartId = cartId;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Integer getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public Integer getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

}
