package com.abstracta.bean;

// Generated 02/12/2013 10:07:39 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Status generated by hbm2java
 */
public class Status implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal statusId;
	private String name;

	public Status() {
	}

	public Status(BigDecimal statusId, String name) {
		this.statusId = statusId;
		this.name = name;
	}

	public BigDecimal getStatusId() {
		return this.statusId;
	}

	public void setStatusId(BigDecimal statusId) {
		this.statusId = statusId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
